query GET_STARSHIP($test: String) {
  Starship(name: $test) {
    name
    hyperdriveRating
    pilots(orderBy: height_DESC) {
      name
      height
      homeworld {
        name
      }
    }
  }
}
