# query GET_STARSHIP($test: String) {
#   Starship(name: $test) {
#     name
#     hyperdriveRating
#     pilots(orderBy: height_DESC) {
#       name
#       height
#       homeworld {
#         name
#       }
#     }
#   }
# }
query GET_STARSHIP {
  # __schema {
  #   types {
  #     kind
  #     name
  #     description
  #   }
  # }

  __type(name: "Film") {
    name
    kind
    fields {
      name
      type {
        name
        kind
      }
    }
  }
  # __type(name: "Film") {
  #   name
  # }
}
